services:
  mariadb:
    image: 'mariadb:latest'
    
    environment:
      MARIADB_DATABASE: mydatabase
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_USER: myuser
      MYSQL_ROOT_HOST: '%'
    ports:
      - published: 3306
        target: 3306
    volumes:
      - 'mariadb-data:/var/lib/mysql'
volumes:
  mariadb-data:
    driver: local
